### ISSUE TITLE
The functions in the PyCeresIK

### ISSUE THREAD

**Issue by Vincent-2017** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#14]
Hello, could you provide a detailed function description in the PyCeresIK?

**Comment by padeler** [comment]
Hello,

PyCeresIK is part of a bigger project and it has functions that are not relevant to our WACV18 paper. If you are interested in a specific function used in WACV18 let me know. I'll try to give you an overview.

**Comment by Vincent-2017** [comment]
`# compute kp using model initial pose`
`points2d = pose_estimator.ba.decodeAndProject(pose_estimator.model.init_pose, clb)`
In the function, the joints angles are used for forward kinematics model and then 3d positions are projected to the image. I want to know the whether the forward kinematics model is included in PyCeresIK and how to use the forward/inverse kinematics model.
`rgbKp = IK.Observations(IK.ObservationType.COLOR, clb, keypoints)`
` obsVec = IK.ObservationsVector([rgbKp, ])`
Could you give a description for the two functions? 
In your paper, the camera parameters are known and used. When you test your method in the youtube vedio, the generic calibration parameters are metioned, I want to know what does the generic calibration parameters mean?

**Comment by Vincent-2017** [comment]
@padeler 
Hello, I use a hand detector to detect all hands in the image, but the results of the left and right hands are indistinguishable. In your paper, the hand detector could distinguish the left hands and right hands, are the codes of the hand detector open source?

**Comment by padeler** [comment]
In the paper we used a hand detector trained to identify 3 classes left hand, right hand and head. Using a pre-trained YOLOv2 network as the base we trained it on a number of frames automatically annotated using the OpenPose method.

Additionally, in order to improve on the detector results in videos like the PMJ song, we used the location of the head as an extra queue for deciding which hand was left and which was right.

Our detector network approach was simplistic (since it was out of the scope of our work), and we did not make it available online, however it should be straight forward to retrain a YOLO (or other) detector for your purposes.
