### ISSUE TITLE
problem with libCore.so

### ISSUE THREAD

**Issue by zhangyanabc** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#17]
Traceback (most recent call last):
  File "handpose.py", line 18, in <module>
    import PyCeresIK as IK
ImportError: /home/zy/code/MonocularRGB_3D_Handpose_WACV18/lib/libCore.so: undefined symbol: _ZN2cv3Mat20updateContinuityFlagEv

I met this problem with libCore.so,how can I solve it?Thanks!

**Comment by padeler** [comment]
It looks like an issue a member of cv::Mat. Probably you have a different (newer?) version of opencv, than the one used to build the binary libCore.so. 

Since the source for these binaries is not available (not open source due to IP restrictions) you will have to use the correct version of opencv (supplied with ubuntu 16.04).

**Comment by zhangyanabc** [comment]
Thanks a lot.I've already had opencv3.4.0 with ubuntu 16.04, what should I do to reference your work?

**Comment by padeler** [comment]
So i assume you got it working on your setup? 
You can reference our work by citing [our paper](http://users.ics.forth.gr/~argyros/mypapers/2018_03_WACV_rgbmonohand.pdf)
