### ISSUE TITLE
description on jt.FindPeaks

### ISSUE THREAD

**Issue by sukun1045** [FORTH-ModelBasedTracker/MonocularRGB_3D_Handpose_WACV18#19]
It looks like the source of PyJointTools is not open and I couldn't make it work on my Python 3.7 platform. Since in my case I only care about 2D estimation, I am interested in how the FindPeaks function is working. Is it possible to describe it a little bit? From my understanding, the simplest idea is for each joint, find the maximum value and its index in the heat-map, then compute the coordinates. Is there any other tricky thing happening? Thank you.

**Comment by padeler** [comment]
Hello,

You can find a python (slow) implementation of the find peaks post processing step here: 
https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation/blob/master/processing.py

The idea is that you apply a gaussian filter over the image and then find the highest peaks. In the case of a single hand it is also much simpler since you expect a single peak for each heatmap.

hope it helps...

**Comment by sukun1045** [comment]
I see. Thank you.
